/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDogeBonusPool } from "./IDogeBonusPool";
export type { IJackpot } from "./IJackpot";
export type { ITreasury } from "./ITreasury";
export type { TonicToken } from "./TonicToken";
