/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as masterChefSol from "./MasterChef.sol";
export type { masterChefSol };
import type * as miningTreasurySol from "./MiningTreasury.sol";
export type { miningTreasurySol };
import type * as mocks from "./mocks";
export type { mocks };
import type * as uniswapV2 from "./uniswap-v2";
export type { uniswapV2 };
