/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMasterChef } from "./IMasterChef";
export type { ITonicDistributor } from "./ITonicDistributor";
export type { MiningTreasury } from "./MiningTreasury";
