/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fraxPayCoreSol from "./FraxPayCore.sol";
export type { fraxPayCoreSol };
import type * as auction from "./auction";
export type { auction };
import type * as classic from "./classic";
export type { classic };
import type * as governance from "./governance";
export type { governance };
import type * as packagedTabs from "./packaged-tabs";
export type { packagedTabs };
import type * as swap from "./swap";
export type { swap };
export type { MockERC20 } from "./MockERC20";
