/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tonicEnglishAuctionV1Sol from "./TonicEnglishAuctionV1.sol";
export type { tonicEnglishAuctionV1Sol };
