/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  BadRecipient,
  BadRecipientInterface,
} from "../../../../contracts/classic/mocks/BadRecipient";

const _abi = [
  {
    stateMutability: "nonpayable",
    type: "fallback",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060a980601d6000396000f3fe6080604052348015600f57600080fd5b506040517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152602160248201527f7468697320636f6e747261637420646f6573206e6f742061636365707420455460448201527f4800000000000000000000000000000000000000000000000000000000000000606482015260840160405180910390fdfea164736f6c634300080a000a";

type BadRecipientConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BadRecipientConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BadRecipient__factory extends ContractFactory {
  constructor(...args: BadRecipientConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<BadRecipient> {
    return super.deploy(overrides || {}) as Promise<BadRecipient>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): BadRecipient {
    return super.attach(address) as BadRecipient;
  }
  override connect(signer: Signer): BadRecipient__factory {
    return super.connect(signer) as BadRecipient__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BadRecipientInterface {
    return new utils.Interface(_abi) as BadRecipientInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BadRecipient {
    return new Contract(address, _abi, signerOrProvider) as BadRecipient;
  }
}
