/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Burnable } from "./IERC20Burnable";
export type { TonicEnglishAuctionV1 } from "./TonicEnglishAuctionV1";
