/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FraxPayCore__factory } from "./FraxPayCore__factory";
export { IERC20__factory } from "./IERC20__factory";
