/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Tonic__factory } from "./ERC20Tonic__factory";
export { KIP7Tonic__factory } from "./KIP7Tonic__factory";
