/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMiningTreasury,
  IMiningTreasuryInterface,
} from "../../../../contracts/swap/MasterChef.sol/IMiningTreasury";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMiningTreasury__factory {
  static readonly abi = _abi;
  static createInterface(): IMiningTreasuryInterface {
    return new utils.Interface(_abi) as IMiningTreasuryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMiningTreasury {
    return new Contract(address, _abi, signerOrProvider) as IMiningTreasury;
  }
}
